function openGUI(renter)
% this function controls all the interface methods
%% initialize ui
format long g
if isempty(renter.Figure)
    renter.Figure = figure('Name','CarRenter','CloseRequestFcn',@closereq);
end
fpos = get(renter.Figure,'Position');
 set(renter.Figure,'defaultUicontrolFontSize',15)
 set(renter.Figure,'defaultUitableFontSize',15)
set(renter.Figure,'Resize','off')

% GUI size cases
switch renter.GUI_Size
    case 'Small'
        set(renter.Figure,'Position',[fpos(1:2),630,300]);
        renter.GUI_SizeNum = 1;
    case 'Medium'
        set(renter.Figure,'Position',[fpos(1:2),810,400]);
        renter.GUI_SizeNum = 2;
    case 'Large'
        set(renter.Figure,'Position',[fpos(1:2),1060,600]);
        renter.GUI_SizeNum = 3;
end % switch

%Set starting Color
clr = [0.9 .44 .37];
set(renter.Figure,'Color',clr);
renter.GUI_ColorNum = 1;
% GUI color cases
switch renter.GUI_Color
    case 'Red'
        clr = [0.9 .44 .37];
        set(renter.Figure,'Color',clr);
        renter.GUI_ColorNum = 1;
    case 'Green'
        clr = [.82 1 .8];
        set(renter.Figure,'Color',clr);
        renter.GUI_ColorNum = 2;
    case 'Blue'
        clr = [.5 1 .93];
        set(renter.Figure,'Color',clr);
        renter.GUI_ColorNum = 3;
    case 'White'
        clr = [1 1 1];
        set(renter.Figure,'Color',clr);
        renter.GUI_ColorNum = 4;
    case 'Grey'
        clr = [.78 .79 .75];
        set(renter.Figure,'Color',clr);
        renter.GUI_ColorNum = 4;
end % switch

%% front page panel
mainPanel = uipanel(renter.Figure,...
    'Units','normalized',...
    'BackgroundColor',clr,...
    'Position',[0 0 1 1]);

% title text
title = uicontrol('Parent',mainPanel,...
    'Style','text',...
    'String','CarRenter',...
    'FontSize',24,...
    'BackgroundColor',clr,...
    'Units','normalized',...
    'Position',[.2 .8 .6 .2]);

% lease car selection
leaseCarButton = uicontrol('Parent',mainPanel,...
    'Callback',@lease_gui,...
    'Style','pushbutton',...
    'String','Lease Your Car',...
    'FontSize',16,...
    'Units','normalized',...
    'Position',[.35 .2 .3 .2]);

% rent car selection
rentCarButton = uicontrol('Parent',mainPanel,...
    'Callback',@rent_gui,...
    'Style','pushbutton',...
    'String','Rent a Car',...
    'FontSize',16,...
    'Units','normalized',...
    'Position',[.35 .6 .3 .2]);

% open options menu
optionsButton = uicontrol('Parent',mainPanel,...
    'Callback',@options_gui,...
    'Style','pushbutton',...
    'String','Options',...
    'Units','normalized',...
    'Position',[.02 .02 .11 .07]);

%% options panel
optionsPanel = uipanel(renter.Figure,...
    'Units','normalized',...
    'BackgroundColor',clr,...
    'Position',[0 0 1 1],...
    'Visible','off');

% color picker
colorChoice = uicontrol('Parent',optionsPanel,...
    'Style','popupmenu',...
    'String',{'Red','Green','Blue','White','Grey'},...
    'Value',renter.GUI_ColorNum,...
    'Units','normalized',...
    'Position',[.3 .7 .4 .15]);

% size picker
sizeChoice = uicontrol('Parent',optionsPanel,...
    'Style','popupmenu',...
    'String',{'Small','Medium','Large'},...
    'Value',renter.GUI_SizeNum,...
    'Units','normalized',...
    'Position',[.3 .4 .4 .15]);

% submit options
optionsButton = uicontrol('Parent',optionsPanel,...
    'Callback',@set_options,...
    'Style','pushbutton',...
    'String','Save Options',...
    'HorizontalAlignment','center',...
    'Units','normalized',...
    'Position',[.3 .02 .2 .15]);

% return to menu
return1 = uicontrol('Parent',optionsPanel,...
    'Callback',@return_1,...
    'Style','pushbutton',...
    'String','Home',...
    'Units','normalized',...
    'Position',[.02 .02 .11 .07]);

%% rent panel
rentPanel = uipanel(renter.Figure,...
    'Units','normalized',...
    'BackgroundColor',clr,...
    'Position',[0 0 1 1],...
    'Visible','off');

% type select text
typeText = uicontrol('Parent',rentPanel,...
    'Style','text',...
    'String','Type',...
    'BackgroundColor',clr,...
    'HorizontalAlignment','left',...
    'Units','normalized',...
    'Position',[.1 .8 .1 .1]);

% type picker
typeChoiceRent = uicontrol('Parent',rentPanel,...
    'Style','popupmenu',...
    'String',{'Truck','Sport','Electric','Normal'},...
    'Units','normalized',...
    'Position',[.1 .7 .4 .15]);

% Zipcode text
zipText = uicontrol('Parent',rentPanel,...
    'Style','text',...
    'String','Zipcode',...
    'BackgroundColor',clr,...
    'HorizontalAlignment','left',...
    'Units','normalized',...
    'Position',[.1 .6 .1 .1]);

% Zipcode picker
zipChoiceRent = uicontrol('Parent',rentPanel,...
    'Style','edit',...
    'String','Enter Zipcode',...
    'Units','normalized',...
    'Position',[.1 .5 .4 .1]);

% search button
search = uicontrol('Parent',rentPanel,...
    'Callback',@search_db,...
    'Style','pushbutton',...
    'String','Search',...
    'Units','normalized',...
    'Position',[.35 .02 .3 .1]);

% return to menu
return2 = uicontrol('Parent',rentPanel,...
    'Callback',@return_2,...
    'Style','pushbutton',...
    'String','Home',...
    'Units','normalized',...
    'Position',[.02 .02 .11 .07]);


%% results panel
resultsPanel = uipanel(renter.Figure,...
    'Units','normalized',...
    'BackgroundColor',clr,...
    'Position',[0 0 1 1],...
    'Visible','off');

% results table
rentTable = uitable('Parent',resultsPanel,...
    'Units','normalized',...
    'RowName',{},...
    'ColumnName',{'Name','Make','Model','Color',...
    'Year','MPG','Start Availability','End Availability','Send Message?'},...
    'Visible','off',...
    'Position',[.01 .2 .98 .8]);


% go to text panel
toText = uicontrol('Parent',resultsPanel,...
    'Callback',@to_text,...
    'Style','pushbutton',...
    'String','Select Automobile',...
    'Units','normalized',...
    'Position',[.35 .02 .3 .14]);

% return to search
return3 = uicontrol('Parent',resultsPanel,...
    'Callback',@return_3,...
    'Style','pushbutton',...
    'String','Edit Search',...
    'Units','normalized',...
    'Position',[.1 .02 .2 .07]);

% return to home
return4 = uicontrol('Parent',resultsPanel,...
    'Callback',@return_4,...
    'Style','pushbutton',...
    'String','Home',...
    'Units','normalized',...
    'Position',[.7 .02 .2 .07]);

%% message panel
messagePanel = uipanel(renter.Figure,...
    'Units','normalized',...
    'BackgroundColor',clr,...
    'Position',[0 0 1 1],...
    'Visible','off');

% Enter email text
emailBox = uicontrol('Parent',messagePanel,...
    'Style','text',...
    'String','Enter your email address:',...
    'HorizontalAlignment','left',...
    'BackgroundColor',clr,...
    'Units','normalized',...
    'Position',[.1 .87 .2 .05]);

% enter email
emailAddress = uicontrol('Parent',messagePanel,...
    'Style','edit',...
    'String','E-Mail Address',...
    'HorizontalAlignment','left',...
    'Units','normalized',...
    'Position',[.3 .88 .3 .05]);

% Enter phone number text
textBox = uicontrol('Parent',messagePanel,...
    'Style','text',...
    'String','Enter your phone number:',...
    'HorizontalAlignment','left',...
    'BackgroundColor',clr,...
    'Units','normalized',...
    'Position',[.1 .80 .2 .05]);

% phone number
phoneNumber = uicontrol('Parent',messagePanel,...
    'Style','edit',...
    'String','Phone Number',...
    'HorizontalAlignment','left',...
    'Units','normalized',...
    'Position',[.3 .81 .3 .05]);

% Enter name text
nameBox = uicontrol('Parent',messagePanel,...
    'Style','text',...
    'String','Enter your full name:',...
    'HorizontalAlignment','left',...
    'BackgroundColor',clr,...
    'Units','normalized',...
    'Position',[.1 .73 .2 .05]);

% Name input
senderName = uicontrol('Parent',messagePanel,...
    'Style','edit',...
    'String','Full Name',...
    'HorizontalAlignment','left',...
    'Units','normalized',...
    'Position',[.3 .74 .3 .05]);

% Message text box
messageText = uicontrol('Parent',messagePanel,...
    'Style','edit',...
    'String','Enter message text here...',...
    'Max',2,'Min',0,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'Units','normalized',...
    'Position',[.1 .22 .8 .46]);

% send text
sendText = uicontrol('Parent',messagePanel,...
    'Callback',@send_text,...
    'Style','pushbutton',...
    'String','Send Message',...
    'Units','normalized',...
    'Position',[.35 .02 .3 .14]);

% return to results
return11 = uicontrol('Parent',messagePanel,...
    'Callback',@return_11,...
    'Style','pushbutton',...
    'String','Back to Results',...
    'Units','normalized',...
    'Position',[.1 .02 .2 .07]);

% return to search
return12 = uicontrol('Parent',messagePanel,...
    'Callback',@return_12,...
    'Style','pushbutton',...
    'String','Edit Search',...
    'Units','normalized',...
    'Position',[.1 .11 .2 .07]);

% return to home
return13 = uicontrol('Parent',messagePanel,...
    'Callback',@return_13,...
    'Style','pushbutton',...
    'String','Home',...
    'Units','normalized',...
    'Position',[.7 .02 .2 .07]);

%% sent panel
sentPanel = uipanel(renter.Figure,...
    'Units','normalized',...
    'BackgroundColor',clr,...
    'Visible','Off',...
    'Position',[0 0 1 1]);

% sent text
sent = uicontrol('Parent',sentPanel,...
    'Style','text',...
    'String','Your message has been sent.',...
    'FontSize',18,...
    'BackgroundColor',clr,...
    'Units','normalized',...
    'Position',[.2 .3 .6 .5]);

% return to home
return14 = uicontrol('Parent',sentPanel,...
    'Callback',@return_14,...
    'Style','pushbutton',...
    'String','Home',...
    'Units','normalized',...
    'Position',[.4 .02 .2 .1]);

%% leasing panel
leasePanel = uipanel(renter.Figure,...
    'Units','normalized',...
    'BackgroundColor',clr,...
    'Visible','Off',...
    'Position',[0 0 1 1]);

% leasing text
lease = uicontrol('Parent',leasePanel,...
    'Style','text',...
    'String','Lease Your Car',...
    'FontSize',24,...
    'BackgroundColor',clr,...
    'Units','normalized',...
    'Position',[.2 .8 .6 .2]);

% load user selection
loadUserButton = uicontrol('Parent',leasePanel,...
    'Callback',@load_user,...
    'Style','pushbutton',...
    'String','Load User',...
    'FontSize',16,...
    'Units','normalized',...
    'Position',[.35 .6 .3 .2]);

% new user selection
newUserButton = uicontrol('Parent',leasePanel,...
    'Callback',@new_user,...
    'Style','pushbutton',...
    'String','New User',...
    'FontSize',16,...
    'Units','normalized',...
    'Position',[.35 .2 .3 .2]);

% return to home
return5 = uicontrol('Parent',leasePanel,...
    'Callback',@return_5,...
    'Style','pushbutton',...
    'String','Home',...
    'Units','normalized',...
    'Position',[.02 .02 .11 .07]);

%% new user panel
newUserPanel = uipanel(renter.Figure,...
    'Units','normalized',...
    'BackgroundColor',clr,...
    'Visible','Off',...
    'Position',[0 0 1 1]);

height = .06;
strtext = {'Name','Phone Number','Email','Zip Code','Password'};

% user info inputs
for i = 1:length(strtext)
    infoinput(i) =  uicontrol('Parent',newUserPanel,...
        'Style','edit',...
        'String',strtext{i},...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.15 (0.99-.08*i) .3 height]);
    
    infotext(i) =  uicontrol('Parent',newUserPanel,...
        'Style','text',...
        'String',strtext{i},...
        'BackgroundColor',clr,...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.02 (0.99-.08*i) .12 height]);
end


years = linspace(2015,2025,11);
months = {'January','February','March','April','May','June','July','August',...
    'September','October','November','December'};
days = linspace(1,31,31);
hours = linspace(0,23,24);

dates={years,months,days,hours};
datetexts={'Year','Month','Date','Hour'};

% dates text
for i = 1:length(datetexts)
    datetext =  uicontrol('Parent',newUserPanel,...
        'Style','text',...
        'String',datetexts{i},...
        'BackgroundColor',clr,...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.03 (0.99-.08*((length(strtext)+1))-.08*i) .14 height]);
end

startdate =  uicontrol('Parent',newUserPanel,...
    'Style','text',...
    'String','Start of Availability',...
    'BackgroundColor',clr,...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',[.1 (0.99-.08*((length(strtext)+1))-.04) .14 height]);

enddate =  uicontrol('Parent',newUserPanel,...
    'Style','text',...
    'String','End of Availability',...
    'BackgroundColor',clr,...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',[.26 (0.99-.08*((length(strtext)+1))-.04) .14 height]);

% date inputs
for i = 1:length(dates)
    startdates(i) =  uicontrol('Parent',newUserPanel,...
        'Style','popupmenu',...
        'String',dates{i},...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.1 (0.99-.08*((length(strtext)+1))-.08*i) .14 height]);
    
    enddates(i) =  uicontrol('Parent',newUserPanel,...
        'Style','popupmenu',...
        'String',dates{i},...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.26 (0.99-.08*((length(strtext)+1))-.08*i) .14 height]);
end

strtext2 = {'Make','Model','Color','Year','MPG'};

% type select text
typeText = uicontrol('Parent',newUserPanel,...
    'Style','text',...
    'String','Type',...
    'BackgroundColor',clr,...
    'HorizontalAlignment','left',...
    'Units','normalized',...
    'Position',[.53 .91 .06 height]);

% type picker
typeChoice = uicontrol('Parent',newUserPanel,...
    'Style','popupmenu',...
    'String',{'Truck','Sport','Electric','Normal'},...
    'Units','normalized',...
    'Position',[.6 .91 .3 height]);

% car info inputs
for i = 1:length(strtext2)
    input(i) =  uicontrol('Parent',newUserPanel,...
        'Style','edit',...
        'String',strtext2{i},...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.6 0.91-.08*i .3 height]);
    
    inputtext(i) =  uicontrol('Parent',newUserPanel,...
        'Style','text',...
        'String',strtext2{i},...
        'BackgroundColor',clr,...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.53 (0.91-.08*i) .06 height]);
end

% add user submit button
addUser = uicontrol('Parent',newUserPanel,...
    'Callback',@add_user,...
    'Style','pushbutton',...
    'String','Submit',...
    'Units','normalized',...
    'Position',[.35 .02 .3 .15]);

% return to home
return6 = uicontrol('Parent',newUserPanel,...
    'Callback',@return_6,...
    'Style','pushbutton',...
    'String','Home',...
    'Units','normalized',...
    'Position',[.02 .02 .11 .07]);

%% added panel
addedUserPanel = uipanel(renter.Figure,...
    'Units','normalized',...
    'BackgroundColor',clr,...
    'Visible','Off',...
    'Position',[0 0 1 1]);

% added text
added = uicontrol('Parent',addedUserPanel,...
    'Style','text',...
    'String','Your car has been added to our databse.',...
    'FontSize',18,...
    'BackgroundColor',clr,...
    'Units','normalized',...
    'Position',[.2 .3 .6 .5]);

% return to home
return7 = uicontrol('Parent',addedUserPanel,...
    'Callback',@return_7,...
    'Style','pushbutton',...
    'String','Home',...
    'Units','normalized',...
    'Position',[.4 .02 .2 .1]);

%% load user panel
loadUserPanel = uipanel(renter.Figure,...
    'Units','normalized',...
    'BackgroundColor',clr,...
    'Visible','Off',...
    'Position',[0 0 1 1]);

% user info inputs
user_name =  uicontrol('Parent',loadUserPanel,...
    'Style','edit',...
    'String','Enter User Name',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',[.3 .6 .4 .1]);

user_pw =  uicontrol('Parent',loadUserPanel,...
    'Style','edit',...
    'String','Enter Password',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',[.3 .4 .4 .1]);

% load user
loadUser = uicontrol('Parent',loadUserPanel,...
    'Callback',@info_change,...
    'Style','pushbutton',...
    'String','Submit',...
    'Units','normalized',...
    'Position',[.35 .02 .3 .15]);

% return to home
return8 = uicontrol('Parent',loadUserPanel,...
    'Callback',@return_8,...
    'Style','pushbutton',...
    'String','Home',...
    'Units','normalized',...
    'Position',[.02 .02 .11 .07]);


%% change info panel
infoChangePanel = uipanel(renter.Figure,...
    'Units','normalized',...
    'BackgroundColor',clr,...
    'Visible','Off',...
    'Position',[0 0 1 1]);

height = .06;
strtext3 = {'Name','Phone Number','Email','Zip Code','Password',''};

% user info inputs
for i = 1:length(strtext3)-1
    infoinput_ch(i) =  uicontrol('Parent',infoChangePanel,...
        'Style','edit',...
        'String',strtext3{i},...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.15 (0.99-.08*i) .3 height]);
    
    infotext(i) =  uicontrol('Parent',infoChangePanel,...
        'Style','text',...
        'String',strtext{i},...
        'BackgroundColor',clr,...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.02 (0.99-.08*i) .12 height]);
end

years = linspace(2015,2025,11);
months = {'January','February','March','April','May','June','July','August',...
    'September','October','November','December'};
days = linspace(1,31,31);
hours = linspace(0,23,24);

startdata={years,months,days,hours};
enddata={years,months,days,hours};
datetexts={'Year','Month','Date','Hour'};

% dates text
for i = 1:length(datetexts)
    datetext =  uicontrol('Parent',infoChangePanel,...
        'Style','text',...
        'String',datetexts{i},...
        'BackgroundColor',clr,...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.03 (0.99-.08*((length(strtext)+1))-.08*i) .14 height]);
end

startdate =  uicontrol('Parent',infoChangePanel,...
    'Style','text',...
    'String','Start of Availability',...
    'BackgroundColor',clr,...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',[.1 (0.99-.08*((length(strtext)+1))-.04) .14 height]);

enddate =  uicontrol('Parent',infoChangePanel,...
    'Style','text',...
    'String','End of Availability',...
    'BackgroundColor',clr,...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',[.26 (0.99-.08*((length(strtext)+1))-.04) .14 height]);

% date inputs
for i = 1:length(dates)
    startdates_ch(i) =  uicontrol('Parent',infoChangePanel,...
        'Style','popupmenu',...
        'String',startdata{i},...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.1 (0.99-.08*((length(strtext)+1))-.08*i) .14 height]);
    
    enddates_ch(i) =  uicontrol('Parent',infoChangePanel,...
        'Style','popupmenu',...
        'String',enddata{i},...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.26 (0.99-.08*((length(strtext)+1))-.08*i) .14 height]);
end

% car info inputs

% type select text
typeText = uicontrol('Parent',infoChangePanel,...
    'Style','text',...
    'String','Type',...
    'BackgroundColor',clr,...
    'HorizontalAlignment','left',...
    'Units','normalized',...
    'Position',[.53 .91 .06 height]);

% type picker
typeChoice_ch = uicontrol('Parent',infoChangePanel,...
    'Style','popupmenu',...
    'String',{'Truck','Sport','Electric','Normal'},...
    'Units','normalized',...
    'Position',[.6 .91 .3 height]);

for i = 1:length(strtext2)
    input_ch(i) =  uicontrol('Parent',infoChangePanel,...
        'Style','edit',...
        'String',strtext2{i},...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.6 0.91-.08*i .3 height]);
    
    inputtext(i) =  uicontrol('Parent',infoChangePanel,...
        'Style','text',...
        'String',strtext2{i},...
        'BackgroundColor',clr,...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[.53 (0.91-.08*i) .06 height]);
end

% submit
changeUser = uicontrol('Parent',infoChangePanel,...
    'Callback',@info_changed,...
    'Style','pushbutton',...
    'String','Submit',...
    'Units','normalized',...
    'Position',[.35 .02 .3 .15]);

% delete button
deleteUser = uicontrol('Parent',infoChangePanel,...
    'Callback',@delete_user,...
    'Style','pushbutton',...
    'String','Delete Account',...
    'Units','normalized',...
    'Position',[.7 .02 .25 .15]);

% return to home
return9 = uicontrol('Parent',infoChangePanel,...
    'Callback',@return_9,...
    'Style','pushbutton',...
    'String','Home',...
    'Units','normalized',...
    'Position',[.02 .02 .11 .07]);

%% changed panel
changedPanel = uipanel(renter.Figure,...
    'Units','normalized',...
    'BackgroundColor',clr,...
    'Visible','Off',...
    'Position',[0 0 1 1]);

% changed text
changed = uicontrol('Parent',changedPanel,...
    'Style','text',...
    'String','Your information has been updated.',...
    'FontSize',18,...
    'BackgroundColor',clr,...
    'Units','normalized',...
    'Position',[.2 .3 .6 .5]);

% return to home
return10 = uicontrol('Parent',changedPanel,...
    'Callback',@return_10,...
    'Style','pushbutton',...
    'String','Home',...
    'Units','normalized',...
    'Position',[.4 .02 .2 .1]);

%% deleted panel
deletedPanel = uipanel(renter.Figure,...
    'Units','normalized',...
    'BackgroundColor',clr,...
    'Visible','Off',...
    'Position',[0 0 1 1]);

% changed text
changed = uicontrol('Parent',deletedPanel,...
    'Style','text',...
    'String','User deleted.',...
    'FontSize',18,...
    'BackgroundColor',clr,...
    'Units','normalized',...
    'Position',[.2 .3 .6 .5]);

% return to home
return15 = uicontrol('Parent',deletedPanel,...
    'Callback',@return_15,...
    'Style','pushbutton',...
    'String','Home',...
    'Units','normalized',...
    'Position',[.4 .02 .2 .1]);

%% sub functions

    function options_gui(a,b) % main -> options
        set(optionsPanel,'Visible','On');
        set(mainPanel,'Visible','Off');
    end

    function lease_gui(a,b) % main -> lease
        set(leasePanel,'Visible','On');
        set(mainPanel,'Visible','Off');
    end

    function rent_gui(a,b) % main -> rent
        set(rentPanel,'Visible','On');
        set(mainPanel,'Visible','Off');
    end

    function search_db(a,b)
        search_type=get(typeChoiceRent,'Value');
        search_zip=get(zipChoiceRent,'String');
        results=getSearchResults(renter.Database,search_type,search_zip);
        assignin('base','results',results)
        if results{1}==false
            h=msgbox('No cars of that type in Zipcode','No Results','error');
        else
            for j=1:size(results,1)
                results{j,end}=false;
            end
            format={'char','numeric','char','char','char','char','char','char','logical'};
            editable=[false false false false false false false false true];
            set(rentTable,'Data',results,'Visible','On','ColumnEditable',editable);
            set(rentTable,'ColumnWidth',{140 'auto' 'auto' 'auto' 50 50 120 120 'auto'})
            set(resultsPanel,'Visible','On');
            set(rentPanel,'Visible','Off');
        end
    end

    function to_text(a,b) % results -> text
        
        
        data=get(rentTable,'data');
        for j=1:size(data,1)
            if data{j,end}==true
                renter.SelectedUsers{end+1}=data(j,:);
            end
        end
        if ~isempty(renter.SelectedUsers)
            
        set(messagePanel,'Visible','On');
        set(resultsPanel,'Visible','Off');
        
        set(emailAddress,'String','Enter your email');
        set(phoneNumber,'String','Enter your phone number');
        set(messageText,'String','Enter your message');
        set(senderName,'String','Enter your name');
        set(zipChoiceRent,'String','Enter Zipcode');
        else
            msgbox('Please select at least one result','Error','modal')
        end
    end

    function send_text(a,b) % text -> sent
        h = waitbar(0,'Please wait...');
        steps = length(renter.SelectedUsers);
        
        set(sentPanel,'Visible','On');
        set(messagePanel,'Visible','Off');
        
        message=get(messageText,'String');
        mailAddress=get(emailAddress,'String');
        phone=get(phoneNumber,'String');
        name=get(senderName,'String');
        
        
        finalMessage=[message, ' My contact info is: ', mailAddress, ', ',phone];
        for i=1:length(renter.SelectedUsers)
            UserAndIndex=findUser(renter.Database,renter.SelectedUsers{i}{1});
            UserInfo=getInfo(UserAndIndex{1});
            Userphone=UserInfo{2};
            Useremail=UserInfo{3};
            waitbar(i/steps);
            sendMail(renter,Useremail,finalMessage,'Car Rental');
            send_text_message(renter,num2str(Userphone),'Verizon','Car Rental',...
                [name,' wants to rent your vehicle. Their contact info is: ', mailAddress, ', ',phone]);
        end
        
        close(h)
        
    end

    function new_user(a,b) % lease -> new
        set(newUserPanel,'Visible','On');
        set(leasePanel,'Visible','Off');
        for j = 1:length(strtext)
            set(infoinput(j),'String',strtext(j))
        end
        strtext2 = {'Make','Model','Color','Year','MPG'};
        for j = 1:length(strtext2)
            set(input(j),'String',strtext2(j))
        end
    end

    function add_user(a,b) % new -> added
        
        % create auto object
        type = get(typeChoice,'Value');
        inputs = get(input,'String');
        
        ma=inputs{1}{1};
        mo=inputs{2}{1};
        co=inputs{3}{1};
        y=inputs{4}{1};
        mpg=inputs{5}{1};
        
        % create date objects
        sdy=get(startdates(1),'Value')+2014;
        sdm=get(startdates(2),'Value');
        sdd=get(startdates(3),'Value');
        sdh=get(startdates(4),'Value')-1;
        
        sd=datetime(sdy,sdm,sdd,sdh,0,0);
        
        edy=get(enddates(1),'Value')+2014;
        edm=get(enddates(2),'Value');
        edd=get(enddates(3),'Value');
        edh=get(enddates(4),'Value')-1;
        ed=datetime(edy,edm,edd,edh,0,0);
        
        auto=Automobile(ma,mo,y,co,mpg,type,sd,ed);
        
        % create user and add to database
        infos=get(infoinput,'String');
        
        nm=infos{1}{1};
        pn=infos{2}{1};
        email=infos{3}{1};
        pn(ismember(pn,' ,.:;!()-'))=[];
        zc=infos{4}{1};
        pw=infos{5}{1};
        
        newuser=User(nm,pn,email,zc,pw,auto);
        AddUser(renter.Database,newuser);
        
        set(addedUserPanel,'Visible','On');
        set(newUserPanel,'Visible','Off');
    end

    function load_user(a,b) % lease -> load
        set(loadUserPanel,'Visible','On');
        set(leasePanel,'Visible','Off');
        set(user_name,'String','Enter Name')
        set(user_pw,'String','Enter Password')
    end

    function info_change(a,b) % load -> change
        name=get(user_name,'String');
        pw=get(user_pw,'String');
        names=getUserNames(renter.Database);
        
        if ~any(ismember(names,name))
            errordlg('Wrong Name, try again','Wrong Name','modal');
        else
            ui_ch=findUser(renter.Database,name);
            %get user's data
            strtext3=ui_ch{1}.getInfo;
            if ~strcmp(pw,strtext3{5})
                errordlg('Wrong password, try again','Wrong password','modal');
            else
                strtext2=strtext3{6}.getInfo;
                startdata=strtext2{7};
                
                sy=year(startdata)-2014;
                sm=month(startdata);
                sd=day(startdata);
                sh=hour(startdata)+1;
                sdd={sy,sm,sd,sh};
                
                enddata=strtext2{8};
                
                ey=year(enddata)-2014;
                em=month(enddata);
                ed=day(enddata);
                eh=hour(enddata)+1;
                edd={ey,em,ed,eh};
                
                %fill in fields
                for j = 1:length(strtext3)-1
                    set(infoinput_ch(j),'String',strtext3(j))
                end
                
                set(infoinput_ch(2),'String',num2str(strtext3{2}))
                
                for j = 1:length(strtext2)-3
                    set(input_ch(j),'String',strtext2(j+1))
                end
                
                for j = 1:4
                    set(startdates_ch(j),'Value',sdd{j})
                    set(enddates_ch(j),'Value',edd{j})
                end

                set(typeChoice_ch,'Value',strtext2{1})
                
                set(infoChangePanel,'Visible','On');
                set(loadUserPanel,'Visible','Off');
            end
        end
    end

    function delete_user(a,b)
        x = inputdlg('Enter your password to delete your account:',...
            'Delete User');
        if strcmp(x,strtext3{5})
            name=get(user_name,'String');
            ui_ch=findUser(renter.Database,name);
            DeleteUser(renter.Database,ui_ch{1});
            set(deletedPanel,'Visible','On');
            set(infoChangePanel,'Visible','Off');
        end
    end

    function info_changed(a,b) % change -> changed
        
        % create auto object
        inputs=get(input_ch,'String');
        newma=inputs{1}{1};
        newmo=inputs{2}{1};
        newco=inputs{3}{1};
        newy=inputs{4}{1};
        newmpg=inputs{5}{1};
        newtype=get(typeChoice_ch,'Value');
        
        % create date objects
        sdy=get(startdates_ch(1),'Value')+2014;
        sdm=get(startdates_ch(2),'Value');
        sdd=get(startdates_ch(3),'Value');
        sdh=get(startdates_ch(4),'Value')-1;
        
        sd=datetime(sdy,sdm,sdd,sdh,0,0);
        
        edy=get(enddates_ch(1),'Value')+2014;
        edm=get(enddates_ch(2),'Value');
        edd=get(enddates_ch(3),'Value');
        edh=get(enddates_ch(4),'Value')-1;
        
        ed=datetime(edy,edm,edd,edh,0,0);
        
        auto=Automobile(newma,newmo,newy,newco,newmpg,newtype,sd,ed);
        
        % update user info
        infos=get(infoinput_ch,'String');
        newnm=infos{1}{1};
        newpn=infos{2};
        newemail=infos{3}{1};
        newpn(ismember(newpn,' ,.:;!()-'))=[];
        
        newzc=infos{4}{1};
        newpw=infos{5}{1};
        ui=findUser(renter.Database,newnm);
        
        updateInfo(ui{1},newnm,newemail,newpn,newzc,newpw,auto)
        
        set(changedPanel,'Visible','On');
        set(infoChangePanel,'Visible','Off');
    end

    function set_options(a,b)
        colors=get(colorChoice,'String');
        newcolor=colors{get(colorChoice,'Value')};
        renter.GUI_Color=newcolor;
        
        sizes=get(sizeChoice,'String');
        newsize=sizes{get(sizeChoice,'Value')};
        renter.GUI_Size=newsize;
        openGUI(renter);
    end

    function return_1(a,b) % options -> main
        set(mainPanel,'Visible','On');
        set(optionsPanel,'Visible','Off');
    end

    function return_2(a,b) % rent -> main
        set(mainPanel,'Visible','On');
        set(rentPanel,'Visible','Off');
        set(zipChoiceRent,'String','Enter Zipcode');
        set(emailAddress,'String','Enter your email');
        set(phoneNumber,'String','Enter your phone number');
        set(messageText,'String','Enter your message');
        
    end

    function return_3(a,b) % results -> rent
        set(rentPanel,'Visible','On');
        set(resultsPanel,'Visible','Off');
    end

    function return_4(a,b) % results -> main
        set(mainPanel,'Visible','On');
        set(resultsPanel,'Visible','Off');
        set(zipChoiceRent,'String','Enter Zipcode');
        set(emailAddress,'String','Enter your email');
        set(phoneNumber,'String','Enter your phone number');
        set(messageText,'String','Enter your message');
    end

    function return_5(a,b) % lease -> main
        set(mainPanel,'Visible','On');
        set(leasePanel,'Visible','Off');
    end

    function return_6(a,b) % new user -> main
        set(mainPanel,'Visible','On');
        set(newUserPanel,'Visible','Off');
    end

    function return_7(a,b) % added user -> main
        set(mainPanel,'Visible','On');
        set(addedUserPanel,'Visible','Off');
    end

    function return_8(a,b) % load user -> main
        set(mainPanel,'Visible','On');
        set(loadUserPanel,'Visible','Off');
    end

    function return_9(a,b) % change info -> main
        set(mainPanel,'Visible','On');
        set(infoChangePanel,'Visible','Off');
    end

    function return_10(a,b) % changed info -> main
        set(mainPanel,'Visible','On');
        set(changedPanel,'Visible','Off');
    end

    function return_11(a,b) % message -> results
        set(resultsPanel,'Visible','On');
        set(messagePanel,'Visible','Off');
        renter.SelectedUsers={};
    end

    function return_12(a,b) % message -> search
        set(rentPanel,'Visible','On');
        set(messagePanel,'Visible','Off');
        renter.SelectedUsers={};
    end

    function return_13(a,b) % message -> main
        set(mainPanel,'Visible','On');
        set(messagePanel,'Visible','Off');
        set(zipChoiceRent,'String','Enter Zipcode');
        set(emailAddress,'String','Enter your email');
        set(phoneNumber,'String','Enter your phone number');
        set(messageText,'String','Enter your message');
        renter.SelectedUsers={};
    end

    function return_14(a,b) % sent -> main
        set(mainPanel,'Visible','On');
        set(sentPanel,'Visible','Off');
        renter.SelectedUsers={};
    end

    function return_15(a,b) % deleted -> main
        set(mainPanel,'Visible','On');
        set(deletedPanel,'Visible','Off');
    end

    function closereq (src,callbackdata) %Close GUI
        renter.saveDatabase('Database');
        delete(renter.Figure)
    end
end